name: hesba
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.5

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # UI & Responsive
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1

  # Connectivity
  connectivity_plus: ^6.1.3

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
