// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnlnGicoFzVLzEAdPTbo8nBC-Q3rzwlds',
    appId: '1:877017690588:web:2389f5dbc7f73a5b545f19',
    messagingSenderId: '877017690588',
    projectId: 'hesba-business',
    authDomain: 'hesba-business.firebaseapp.com',
    storageBucket: 'hesba-business.firebasestorage.app',
    measurementId: 'G-SJ8PM1KSKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-i2ZUVDajVTsAZuctQRIRYDf7GF0aVqs',
    appId: '1:877017690588:android:60325e8186b7900a545f19',
    messagingSenderId: '877017690588',
    projectId: 'hesba-business',
    storageBucket: 'hesba-business.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfRh_j02TSTwVZb5QlzMIkToqm8XsPVTQ',
    appId: '1:877017690588:ios:8527e9f645ca8adb545f19',
    messagingSenderId: '877017690588',
    projectId: 'hesba-business',
    storageBucket: 'hesba-business.firebasestorage.app',
    iosBundleId: 'com.zerobugs.hesba',
  );
}
